### ISSUE TITLE
java.lang.IllegalThreadStateException

### ISSUE THREAD

**Issue by beartistic** [4eRTuk/audioview#10]
I used AudioView2, when start、pause and then start again crashed
Log :
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: biz.seeyou, PID: 2982
                  java.lang.IllegalThreadStateException
                      at java.lang.Thread.start(Thread.java:744)
                      at com.keenfin.audioview.AudioService.startUpdateThread(AudioService.java:175)
                      at com.keenfin.audioview.AudioService.start(AudioService.java:344)
                      at com.keenfin.audioview.AudioService.controlAudio(AudioService.java:216)
                      at com.keenfin.audioview.AudioView2.onClick(AudioView2.java:209)
                      at android.view.View.performClick(View.java:6291)
                      at android.view.View$PerformClick.run(View.java:24931)
                      at android.os.Handler.handleCallback(Handler.java:808)
                      at android.os.Handler.dispatchMessage(Handler.java:101)
                      at android.os.Looper.loop(Looper.java:166)
                      at android.app.ActivityThread.main(ActivityThread.java:7529)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by beartistic** [comment]
ignore above...
1.2 is ok
